apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.example
spec:
  group: example
  version: v1alpha1
  names:
    kind: Application
    plural: Applications
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            applicationId:
              type: integer
              minimum: 1
              maximum: 10
